### ISSUE TITLE
Display success / error in the form

### ISSUE THREAD

**Issue by neilbradley** [erikreagan/Catch-All-PHP-Form-Processor#1]
Hey Erik,

Would it be possible to get this to display the error or success/thank you message within the form after clicking submit?

Thanks,
Neil

**Comment by erikreagan** [comment]
Hi Neil,

Unfortunately it's not possible without some hefty changes to the script.

I haven't worked on this script in ages and don't intent to pick it back up from its current state. You are welcome to fork and modify as needed.

Best,
Erik
